---
title: AirBnB Santiago
author: Ricardo Villarreal
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: simplex
runtime: shiny
---

```{r library, include=FALSE}
library(tidyverse)
library(readr)
library(leaflet)
library(highcharter)
library(stringr)
library(flexdashboard)
library(shiny)
library(htmltools)
```


```{r}
abnb <- read_csv("listings.csv", na = c("N/A", ""))

abnb <- abnb %>%
  select(name,
         url = listing_url,
         comuna = neighbourhood_cleansed, 
         latitude,
         longitude,
         tipo = room_type,
         price,
         reviews = number_of_reviews,
         score = review_scores_rating) %>%
  mutate(price2 = as.numeric(str_remove_all(price, "[,\\$]")),
         price = str_remove_all(price, "\\.00"),
         price = str_replace(price, ",", "."),
         tipo = case_when(tipo == "Entire home/apt" ~ "Casa/dpto completo",
                          tipo == "Private room" ~ "Pieza privada",
                          tipo == "Shared room" ~ "Pieza compartida",
                          tipo == "Hotel room" ~ "Hotel"),
         mylabel = ifelse(is.na(score), 
                          paste0("<b><a href='", url, "'>", htmlEscape(name), "</a></b>",
                          "<br/>", tipo,
                          "<br/>Precio: ", price,
                          "<br/>Reviews: ", reviews),
                          paste0("<b><a href='", url, "'>", htmlEscape(name), "</a></b>",
                          "<br/>", tipo,
                          "<br/>Precio: ", price,
                          "<br/>Rating: ", score, "%",
                          "<br/>Reviews: ", reviews))) %>%
  filter(price2 < quantile(price2, 0.975) &
           price2 > quantile(price2, 0.025))


get_comuna <- function(){
  if (input$comune == "Gran Santiago") {
    return(comunas)
  } else {
    return(input$comune)
  }
}

get_tipo <- function(){
  if (input$typo == "Todos") {
    return(tipos)
  } else {
    return(input$typo)
  }
}
```






sidebar {.sidebar}
=====================================  

### Filtros

Seleccione la comuna y el tipo de arriendo que desea analizar.
```{r}
comunas <- c("Gran Santiago", unique(abnb$comuna))
label1 <- "Comuna"
selectInput("comune", label = label1,
            choices = comunas, selected = comunas[1])

label2 <- "Tipo de arriendo"
tipos <- c("Todos", unique(abnb$tipo))
selectInput("typo", label = label2,
            choices = tipos, selected = tipos[1])

```
*Nota:* La base de datos AirBnB fue obtenida de *[insideairbnb.com](http://insideairbnb.com).*
Se eliminaron las observaciones cuyo precio se encontraban sobre el percentil 97,5 y bajo el percentil 2,5.
Este proyecto fue creado solamente con fines educativos.


Listado
=====================================


Row 
-------------------------------------

### Localidad {data-height=175}

```{r}
renderValueBox({
  
  localidad <- input$comune
    
  
  valueBox(
    value = localidad,
    icon = "fa-map-marker-alt"
  )
  
})
```


### Anuncios {data-height=175}

```{r}
renderValueBox({
  
  filtro_tipo <- get_tipo()
  filtro_comuna <- get_comuna()
  
  cantidad <- abnb %>%
    filter(comuna %in% filtro_comuna &
             tipo %in% filtro_tipo) %>%
    nrow() %>%
    prettyNum(big.mark = ".", small.mark = ",")
    
  
  valueBox(
    value = cantidad,
    icon = "ion-android-home"
  )
  
})
```




### Valoración Promedio {.value-box}

```{r}
renderValueBox({
  filtro_tipo <- get_tipo()
  filtro_comuna <- get_comuna()
  
  rating <- abnb %>%
    filter(comuna %in% filtro_comuna &
             tipo %in% filtro_tipo) %>%
    .[["score"]] %>%
    mean(na.rm = TRUE) %>%
    round(2) %>%
    prettyNum(big.mark = ".", decimal.mark = ",") %>%
    paste("%")
    
  
  valueBox(
    value = rating,
    icon = "ion-ios-star"
  )
  
})
```

Row
-------------------------------------
### 
```{r}
renderLeaflet({
  filtro_tipo <- get_tipo()
  filtro_comuna <- get_comuna()
  
  abnb %>%
    filter(comuna %in% filtro_comuna &
             tipo %in% filtro_tipo) %>%
    leaflet() %>%
    addTiles() %>%  
    addMarkers(popup = ~mylabel,
               clusterOptions = markerClusterOptions())
  })
```


###


```{r}
renderHighchart({
  filtro_tipo <- get_tipo()
  filtro_comuna <- get_comuna()
  
  
  titulo <- paste("Precios en", input$comune)
  subtitulo <- paste("Categoría:", input$typo)
  
  abnb %>%
    filter(comuna %in% filtro_comuna &
             tipo %in% filtro_tipo) %>%
    .[["price2"]] %>%
  hchart(color = "#B71C1C", borderColor = "black") %>%
    hc_add_theme(hc_theme_flat()) %>%
      hc_legend(enabled = FALSE) %>%
    hc_title(text = titulo, align = "left") %>%
    hc_subtitle(text = subtitulo, align = "left") %>%
    hc_yAxis(title = list(text = "Cantidad")) %>%
    hc_xAxis(title = list(text = "Precio"))
})
```


